# --- roles/jenkins_ssh_key/defaults/main.yml ---
---
jenkins_ssh_key_name: "jenkins_ec2_key"
jenkins_user: "jenkins"
jenkins_home: "/var/lib/jenkins"
jenkins_ssh_dir: "{{ jenkins_home }}/.ssh"
jenkins_private_key_path: "{{ jenkins_ssh_dir }}/{{ jenkins_ssh_key_name }}"
jenkins_public_key_path: "{{ jenkins_private_key_path }}.pub"

dockerhub_username: "azubeq"
dockerhub_token: "dckr_pat_g57t8  QWAOn3Y rn4KXS BD2i ZYl0c"
